# SNUH 호스트 목록
# 형식: IP주소  호스트명  # 설명
# 빈 줄과 #으로 시작하는 줄은 무시됩니다.

# ================= 22 server - supreme web =================
172.26.71.22    dpu22.snuh.org

# ================= 59 server - supreme was =================
172.26.71.22    ums.snuh.org
172.26.71.22    supreme-stg.snuh.org
172.26.71.22    dpu59.snuh.org

# ================= 28 server - etl =================
172.26.71.22    batch.snuh.org
172.26.71.22    elastic.snuh.org
172.26.71.22    elm.snuh.org
172.26.71.22    extract.snuh.org
172.26.71.22    massiver.snuh.org
172.26.71.22    pentaho.snuh.org
172.26.71.22    rid.snuh.org
172.26.71.22    rid-stg.snuh.org
172.26.71.22    dpu28.snuh.org

# ================= 63 server - idp =================
172.26.71.22    rex-idp.snuh.org
172.26.71.22    idp-stg.snuh.org
172.26.71.22    dpu63.snuh.org

# ================= 60 server - cohortmarts =================
172.26.71.22    cohortmarts-stg.snuh.org
172.26.71.22    cohortmarts.snuh.org
172.26.71.22    dpu60.snuh.org

# ================= 61 server - deview =================
172.26.71.22    deview.snuh.org
172.26.71.22    deview-stg.snuh.org
172.26.71.22    dpu61.snuh.org

# ================= 62 server - supreme cdm =================
172.26.71.22    dpu62.snuh.org

# ================= 기타 =================
172.26.33.25    dpu.snuh.org
172.26.33.25    supreme.snuh.org

172.26.33.28    metadb.snuh.org
172.26.33.28    cdwdb.snuh.org
172.26.33.28    hisdb.snuh.org
172.26.33.28    crisdb.snuh.org
